// AUTO-GENERATED by scripts/generate-jxa-types.ts
// Source: vendor/OmniFocus.sdef
// Run `pnpm generate:jxa-types` to regenerate.
// To refresh the .sdef snapshot from the live OmniFocus.app, run
// `pnpm sync:sdef` first.
//
// Coverage: 47 classes,
//           199 properties,
//           54 elements.

interface JxaCollection<T> extends Array<T> {
  /** JXA element-query: fetch a specifier by id. Lazy — throws (-1728) on next access if id is unknown. */
  byId(id: string): T;
  /** JXA element-query: filter by sdef-attribute predicate. Returns a thunk; call it to evaluate. */
  whose(filter: Record<string, unknown>): () => T[];
  /** JXA element-query: random access. */
  at(idx: number): T;
}

/** OmniFocus 'application' class (sdef code: capp). */
interface Application {
  /** [read-only] The name of the application. */
  name(): string;
  /** [read-only] The version number of the application. */
  version(): string;
  /** [read-only] This is the build number of the application, for example 63.1 or 63. Major and minor versions are separated by a dot. So 63.10 comes after 63.1. */
  buildNumber(): string;
  /** The current time offset from a reference date. Useful for timing scripts. */
  currentTimeOffset(): number;
  /** The user's default document. */
  defaultDocument(): Document;
  /** The Quick Entry panel for the default document. */
  quickEntry(): QuickEntryTree;
  /** [read-only] The names of all available perspectives in the default document. */
  perspectiveNames(): unknown;
  /** child collection of 'document' */
  documents: JxaCollection<Document> & (() => JxaCollection<Document>);
  /** child collection of 'window' */
  windows: JxaCollection<Window> & (() => JxaCollection<Window>);
  /** child collection of 'perspective' */
  perspectives: JxaCollection<Perspective> & (() => JxaCollection<Perspective>);
  /** child collection of 'preference' */
  preferences: JxaCollection<Preference> & (() => JxaCollection<Preference>);
}

/** OmniFocus 'document' class (sdef code: docu). */
interface Document {
  /** [read-only] Its name. */
  name(): string;
  /** [read-only] Has it been modified since the last save? */
  modified(): boolean;
  /** [read-only] Its location on disk, if it has one. */
  file(): unknown;
  /** [read-only] The document's unique identifier. */
  id(): string;
  /** [read-only] Whether the document can undo the most recent command. */
  canUndo(): boolean;
  /** [read-only] Whether the document can redo the most recently undone command. */
  canRedo(): boolean;
  /** Whether the document will autosave. */
  willAutosave(): boolean;
  /** Whether the document will write compressed transactions to disk; defaults to true. */
  compressesTransactions(): boolean;
  /** Whether the document will write computed summary information when writing transactions. */
  includesSummaries(): boolean;
  /** [read-only] True if the document is currently syncing, false otherwise. */
  syncing(): boolean;
  /** [read-only] Date of the last sync. */
  lastSyncDate(): Date;
  /** [read-only] Error message (if any) for the last sync. */
  lastSyncError(): string;
  /** The Quick Entry panel for the document. */
  quickEntry(): QuickEntryTree;
  /** If set, automatic cleanup of inbox items won't happen. */
  disableAutomaticInboxCleanup(): boolean;
  /** [read-only] The document's path on disk. */
  path(): string;
  /** [read-only] The names of all available perspectives in this document. */
  perspectiveNames(): unknown;
  /** child collection of 'setting' */
  settings: JxaCollection<Setting> & (() => JxaCollection<Setting>);
  /** child collection of 'document window' */
  documentWindows: JxaCollection<DocumentWindow> & (() => JxaCollection<DocumentWindow>);
  /** child collection of 'section' */
  sections: JxaCollection<Section> & (() => JxaCollection<Section>);
  /** child collection of 'folder' */
  folders: JxaCollection<Folder> & (() => JxaCollection<Folder>);
  /** child collection of 'project' */
  projects: JxaCollection<Project> & (() => JxaCollection<Project>);
  /** child collection of 'tag' */
  tags: JxaCollection<Tag> & (() => JxaCollection<Tag>);
  /** child collection of 'deprecated context' */
  deprecatedContexts: JxaCollection<DeprecatedContext> & (() => JxaCollection<DeprecatedContext>);
  /** child collection of 'inbox task' */
  inboxTasks: JxaCollection<InboxTask> & (() => JxaCollection<InboxTask>);
  /** child collection of 'task' */
  tasks: JxaCollection<Task> & (() => JxaCollection<Task>);
  /** child collection of 'flattened task' */
  flattenedTasks: JxaCollection<FlattenedTask> & (() => JxaCollection<FlattenedTask>);
  /** child collection of 'flattened project' */
  flattenedProjects: JxaCollection<FlattenedProject> & (() => JxaCollection<FlattenedProject>);
  /** child collection of 'flattened folder' */
  flattenedFolders: JxaCollection<FlattenedFolder> & (() => JxaCollection<FlattenedFolder>);
  /** child collection of 'flattened tag' */
  flattenedTags: JxaCollection<FlattenedTag> & (() => JxaCollection<FlattenedTag>);
  /** child collection of 'perspective' */
  perspectives: JxaCollection<Perspective> & (() => JxaCollection<Perspective>);
}

/** OmniFocus 'window' class (sdef code: cwin). */
interface Window {
  /** [read-only] The document whose contents are displayed in the window. */
  document(): Document;
  /** [read-only] The title of the window. */
  name(): string;
  /** [read-only] The unique identifier of the window. */
  id(): number;
  /** The index of the window, ordered front to back. */
  index(): number;
  /** The bounding rectangle of the window. */
  bounds(): unknown;
  /** [read-only] Does the window have a close button? */
  closeable(): boolean;
  /** [read-only] Does the window have a minimize button? */
  miniaturizable(): boolean;
  /** Is the window minimized right now? */
  miniaturized(): boolean;
  /** [read-only] Can the window be resized? */
  resizable(): boolean;
  /** Is the window visible right now? */
  visible(): boolean;
  /** [read-only] Does the window have a zoom button? */
  zoomable(): boolean;
  /** Is the window zoomed right now? */
  zoomed(): boolean;
}

/** OmniFocus 'document window' class (sdef code: FCdw). */
interface DocumentWindow extends Window {
  /** The search term in the toolbar. If there is no search toolbar item, this will return missing value instead of an empty string and setting it will cause an error. */
  searchTerm(): string;
  /** The selected tab in the sidebar. */
  selectedSidebarTab(): unknown;
  /** [read-only] The tree of objects in the window sidebar. */
  sidebar(): SidebarTree;
  /** [read-only] The tree of objects in the main window content. */
  content(): ContentTree;
  /** The name of a perspective. */
  perspectiveName(): string;
  /** A list of the projects and folders forming the project focus of this document window. */
  focus(): FocusSections;
}

/** OmniFocus 'quick entry tree' class (sdef code: FCQw). */
interface QuickEntryTree extends Tree {
  /** [read-only] Whether the quick entry panel is currently visible. */
  visible(): boolean;
  /** child collection of 'folder' */
  folders: JxaCollection<Folder> & (() => JxaCollection<Folder>);
  /** child collection of 'project' */
  projects: JxaCollection<Project> & (() => JxaCollection<Project>);
  /** child collection of 'tag' */
  tags: JxaCollection<Tag> & (() => JxaCollection<Tag>);
  /** child collection of 'deprecated context' */
  deprecatedContexts: JxaCollection<DeprecatedContext> & (() => JxaCollection<DeprecatedContext>);
  /** child collection of 'inbox task' */
  inboxTasks: JxaCollection<InboxTask> & (() => JxaCollection<InboxTask>);
}

/** OmniFocus 'setting' class (sdef code: FCos). */
interface Setting {
  /** [read-only] The identifier of the setting. */
  id(): string;
  /** The current value of the setting. */
  value(): string;
  /** The default value of the setting. */
  defaultValue(): string;
}

/** OmniFocus 'focus sections' class (sdef code: FCFS). */
interface FocusSections {
  /** child collection of 'item' */
  items: JxaCollection<unknown> & (() => JxaCollection<unknown>);
}

/** OmniFocus 'section' class (sdef code: FCSX). */
interface Section {
  /** [read-only] The identifier of the project or folder. */
  id(): string;
  /** The name of the project or folder. */
  name(): string;
}

/** OmniFocus 'folder' class (sdef code: FCAr). */
interface Folder extends Section {
  /** [read-only] The identifier of the folder. */
  id(): string;
  /** The name of the folder. */
  name(): string;
  /** The note of the folder. */
  note(): string;
  /** Set if the folder is currently hidden. */
  hidden(): boolean;
  /** [read-only] Set if the folder is currently hidden or any of its container folders are hidden. */
  effectivelyHidden(): boolean;
  /** [read-only] When the folder was created. */
  creationDate(): Date;
  /** [read-only] When the folder was last modified. */
  modificationDate(): Date;
  /** [read-only] The containing folder or document. */
  container(): Document;
  /** [read-only] The containing document or quick entry tree of the object. */
  containingDocument(): Document;
  /** child collection of 'section' */
  sections: JxaCollection<Section> & (() => JxaCollection<Section>);
  /** child collection of 'folder' */
  folders: JxaCollection<Folder> & (() => JxaCollection<Folder>);
  /** child collection of 'project' */
  projects: JxaCollection<Project> & (() => JxaCollection<Project>);
  /** child collection of 'flattened project' */
  flattenedProjects: JxaCollection<FlattenedProject> & (() => JxaCollection<FlattenedProject>);
  /** child collection of 'flattened folder' */
  flattenedFolders: JxaCollection<FlattenedFolder> & (() => JxaCollection<FlattenedFolder>);
}

/** OmniFocus 'tag' class (sdef code: FCtg). */
interface Tag {
  /** The identifier of the tag. */
  id(): string;
  /** The name of the tag. */
  name(): string;
  /** The note of the tag. */
  note(): string;
  /** If false, tasks associated with this tag will be skipped when determining the next action for a project. */
  allowsNextAction(): boolean;
  /** Set if the tag is currently hidden. */
  hidden(): boolean;
  /** [read-only] Set if the tag is currently hidden or any of its container tags are hidden. */
  effectivelyHidden(): boolean;
  /** [read-only] The containing tag. */
  container(): Tag;
  /** [read-only] A count of the number of unblocked and incomplete tasks of this tag and all its active descendent tags. */
  availableTaskCount(): number;
  /** [read-only] A count of the number of incomplete tasks of this tag and all its active descendent tags. */
  remainingTaskCount(): number;
  /** [read-only] The containing document or quick entry tree of the object. */
  containingDocument(): Document;
  /** The physical location associated with the tag. */
  location(): unknown;
  /** child collection of 'tag' */
  tags: JxaCollection<Tag> & (() => JxaCollection<Tag>);
  /** child collection of 'deprecated context' */
  deprecatedContexts: JxaCollection<DeprecatedContext> & (() => JxaCollection<DeprecatedContext>);
  /** child collection of 'flattened tag' */
  flattenedTags: JxaCollection<FlattenedTag> & (() => JxaCollection<FlattenedTag>);
  /** child collection of 'task' */
  tasks: JxaCollection<Task> & (() => JxaCollection<Task>);
  /** child collection of 'available task' */
  availableTasks: JxaCollection<AvailableTask> & (() => JxaCollection<AvailableTask>);
  /** child collection of 'remaining task' */
  remainingTasks: JxaCollection<RemainingTask> & (() => JxaCollection<RemainingTask>);
}

/** OmniFocus 'deprecated context' class (sdef code: FCct). */
interface DeprecatedContext extends Tag {
}

/** OmniFocus 'project' class (sdef code: FCpr). */
interface Project extends Section {
  /** The identifier of the project. */
  id(): string;
  /** [read-only] The next actionable child of this project. */
  nextTask(): Task;
  /** When the project was last reviewed. */
  lastReviewDate(): Date;
  /** When the project should next be reviewed. Setting this to missing value will set the review date based off the last review date and review interval. */
  nextReviewDate(): Date;
  /** The review interval for the project. */
  reviewInterval(): unknown;
  /** The status of the project. */
  status(): unknown;
  /** [read-only] The effective status of the project. */
  effectiveStatus(): unknown;
  /** True if the project contains singleton actions. */
  singletonActionHolder(): boolean;
  /** True if the project is the default holder of sington actions. Only one project can have this flag set; setting it on a project will clear it on any other project having it. Setting this to true will set 'singleton action holder' to true if not already so set. */
  defaultSingletonActionHolder(): boolean;
  /** [read-only] The containing folder or document. */
  container(): Document;
  /** [read-only] The folder of the project, or missing value if it is contained directly by the document. */
  folder(): Folder;
  /** The name of the project. */
  name(): string;
  /** The note of the project. */
  note(): string;
  /** [read-only] The containing document or quick entry tree of the object. */
  containingDocument(): Document;
  /** The project's first tag. Setting this will remove the current first tag on the project, if any and move or add the new tag as the first tag on the project. Setting this to missing value will remove the current first tag and leave any other remaining tags. */
  primaryTag(): Tag;
  /** If true, complete when children are completed. */
  completedByChildren(): boolean;
  /** If true, any children are sequentially dependent. */
  sequential(): boolean;
  /** True if flagged */
  flagged(): boolean;
  /** [read-only] True if the project has a project that must be completed prior to it being actionable. */
  blocked(): boolean;
  /** When the project was created. This can only be set when the object is still in the inserted state. For objects created in the document, it can be passed with the creation properties. For objects in a quick entry tree, it can be set until the quick entry panel is saved. */
  creationDate(): Date;
  /** [read-only] When the project was last modified. */
  modificationDate(): Date;
  /** When the project should become available for action. */
  deferDate(): Date;
  /** [read-only] When the project should become available for action (including inherited). */
  effectiveDeferDate(): Date;
  /** The date at which work for this project is intended. */
  plannedDate(): Date;
  /** [read-only] The date at which work for this project is intended (including inherited). */
  effectivePlannedDate(): Date;
  /** When the project must be finished. */
  dueDate(): Date;
  /** [read-only] When the project must be finished (including inherited). */
  effectiveDueDate(): Date;
  /** When set, the due date and defer date properties will use floating time zones. (Note: if a Task has no due or defer dates assigned, this property will revert to the database’s default setting.) */
  shouldUseFloatingTimeZone(): boolean;
  /** The project's date of completion. This can only be modified on a completed project to backdate the completion date. */
  completionDate(): Date;
  /** [read-only] True if the project is completed. Use the &quot;mark complete&quot; and &quot;mark incomplete&quot; commands to change a project's status. */
  completed(): boolean;
  /** [read-only] True if the project is completed */
  effectivelyCompleted(): boolean;
  /** The date the project was dropped. This can only be modified on a dropped project to backdate the dropped date. */
  droppedDate(): Date;
  /** [read-only] True if the project is dropped. Use the &quot;mark dropped&quot; and &quot;mark incomplete&quot; commands to change a project's status. */
  dropped(): boolean;
  /** [read-only] True if the project is dropped */
  effectivelyDropped(): boolean;
  /** The estimated time, in whole minutes, that this project will take to finish. */
  estimatedMinutes(): number;
  /** The repetition interval of the project, or missing value if it does not repeat. This property is deprecated in favor of “repetition rule” and is here only for backwards compatibility with existing scripts. */
  repetition(): unknown;
  /** The repetition rule for this project, or missing value if it does not repeat. */
  repetitionRule(): unknown;
  /** [read-only] The next defer date if this project repeats on a fixed schedule and it has a defer date. */
  nextDeferDate(): Date;
  /** [read-only] The next planned date if this project repeats on a fixed schedule and it has a planned date. */
  nextPlannedDate(): Date;
  /** [read-only] The next due date if this project repeats on a fixed schedule and it has a due date. */
  nextDueDate(): Date;
  /** [read-only] The number of direct children of this project. */
  numberOfTasks(): number;
  /** [read-only] The number of available direct children of this project. */
  numberOfAvailableTasks(): number;
  /** [read-only] The number of completed direct children of this project. */
  numberOfCompletedTasks(): number;
}

/** OmniFocus 'task' class (sdef code: FCac). */
interface Task {
  /** The identifier of the task. */
  id(): string;
  /** The name of the task. */
  name(): string;
  /** The note of the task. */
  note(): string;
  /** [read-only] The containing task, project or document. */
  container(): Document;
  /** [read-only] The task's project, up however many levels of parent tasks. Inbox tasks aren't considered contained by their provisionalliy assigned container, so if the task is actually an inbox task, this will be missing value. */
  containingProject(): Project;
  /** [read-only] The task holding this task. If this is missing value, then this is a top level task -- either the root of a project or an inbox item. */
  parentTask(): Task;
  /** [read-only] The containing document or quick entry tree of the object. */
  containingDocument(): Document;
  /** [read-only] Returns true if the task itself is an inbox task or if the task is contained by an inbox task. */
  inInbox(): boolean;
  /** The task's first tag. Setting this will remove the current first tag on the task, if any and move or add the new tag as the first tag on the task. Setting this to missing value will remove the current first tag and leave any other remaining tags. */
  primaryTag(): Tag;
  /** If true, complete when children are completed. */
  completedByChildren(): boolean;
  /** If true, any children are sequentially dependent. */
  sequential(): boolean;
  /** True if flagged */
  flagged(): boolean;
  /** [read-only] If the task is the next task of its containing project, next is true. */
  next(): boolean;
  /** [read-only] True if the task has a task that must be completed prior to it being actionable. */
  blocked(): boolean;
  /** When the task was created. This can only be set when the object is still in the inserted state. For objects created in the document, it can be passed with the creation properties. For objects in a quick entry tree, it can be set until the quick entry panel is saved. */
  creationDate(): Date;
  /** [read-only] When the task was last modified. */
  modificationDate(): Date;
  /** When the task should become available for action. */
  deferDate(): Date;
  /** [read-only] When the task should become available for action (including inherited). */
  effectiveDeferDate(): Date;
  /** The date at which work for this task is intended. */
  plannedDate(): Date;
  /** [read-only] The date at which work for this task is intended (including inherited). */
  effectivePlannedDate(): Date;
  /** When the task must be finished. */
  dueDate(): Date;
  /** [read-only] When the task must be finished (including inherited). */
  effectiveDueDate(): Date;
  /** When set, the due date and defer date properties will use floating time zones. (Note: if a Task has no due or defer dates assigned, this property will revert to the database’s default setting.) */
  shouldUseFloatingTimeZone(): boolean;
  /** The task's date of completion. This can only be modified on a completed task to backdate the completion date. */
  completionDate(): Date;
  /** [read-only] True if the task is completed. Use the &quot;mark complete&quot; and &quot;mark incomplete&quot; commands to change a task's status. */
  completed(): boolean;
  /** [read-only] True if the task is completed, or any of it's containing tasks or project are completed. */
  effectivelyCompleted(): boolean;
  /** The date the task was dropped. This can only be modified on a dropped task to backdate the dropped date. */
  droppedDate(): Date;
  /** [read-only] True if the task is dropped. Use the &quot;mark dropped&quot; and &quot;mark incomplete&quot; commands to change a task's status. */
  dropped(): boolean;
  /** [read-only] True if the task is dropped, or any of it's containing tasks or project are dropped. */
  effectivelyDropped(): boolean;
  /** The estimated time, in whole minutes, that this task will take to finish. */
  estimatedMinutes(): number;
  /** The repetition interval of the task, or missing value if it does not repeat. This property is deprecated in favor of “repetition rule” and is here only for backwards compatibility with existing scripts. */
  repetition(): unknown;
  /** The repetition rule for this task, or missing value if it does not repeat. */
  repetitionRule(): unknown;
  /** [read-only] The next defer date if this task repeats on a fixed schedule and it has a defer date. */
  nextDeferDate(): Date;
  /** [read-only] The next planned date if this task repeats on a fixed schedule and it has a planned date. */
  nextPlannedDate(): Date;
  /** [read-only] The next due date if this task repeats on a fixed schedule and it has a due date. */
  nextDueDate(): Date;
  /** [read-only] The number of direct children of this task. */
  numberOfTasks(): number;
  /** [read-only] The number of available direct children of this task. */
  numberOfAvailableTasks(): number;
  /** [read-only] The number of completed direct children of this task. */
  numberOfCompletedTasks(): number;
  /** A simple textual archive of a task that can be used to create, update and distributed tasks. Please see the documentation for more information. */
  transportText(): string;
  /** child collection of 'tag' */
  tags: JxaCollection<Tag> & (() => JxaCollection<Tag>);
  /** child collection of 'task' */
  tasks: JxaCollection<Task> & (() => JxaCollection<Task>);
  /** child collection of 'flattened task' */
  flattenedTasks: JxaCollection<FlattenedTask> & (() => JxaCollection<FlattenedTask>);
}

/** OmniFocus 'forecast sidebar tree' class (sdef code: FCFt). */
interface ForecastSidebarTree extends SidebarTree {
  /** child collection of 'forecast day' */
  forecastDays: JxaCollection<ForecastDay> & (() => JxaCollection<ForecastDay>);
}

/** OmniFocus 'forecast day' class (sdef code: FCdy). */
interface ForecastDay {
  /** The identifier of the task. */
  id(): string;
  /** A display name for the forecast day. */
  name(): string;
  /** True if the forecast day has no content at all. Note that some content will not cause a badge to be shown in the sidebar, and some content is controlled by user preferences. */
  empty(): boolean;
  /** The count shown in the sidebar for this forecast day, or zero if there is no count shown. */
  badgeCount(): number;
}

/** OmniFocus 'available task' class (sdef code: FCat). */
interface AvailableTask extends Task {
}

/** OmniFocus 'remaining task' class (sdef code: FC0T). */
interface RemainingTask extends Task {
}

/** OmniFocus 'inbox task' class (sdef code: FCit). */
interface InboxTask extends Task {
  /** Inbox tasks (those contained directly by the document) have a provisionally set container that is made final by the 'compact' command. This allows you to set and get said container. The container must be either a task (not in the inbox or contained by an inbox task), a project or 'missing value'. */
  assignedContainer(): unknown;
}

/** OmniFocus 'flattened task' class (sdef code: FCft). */
interface FlattenedTask extends Task {
}

/** OmniFocus 'flattened project' class (sdef code: FCfx). */
interface FlattenedProject extends Project {
}

/** OmniFocus 'flattened folder' class (sdef code: FCff). */
interface FlattenedFolder extends Folder {
}

/** OmniFocus 'flattened tag' class (sdef code: FCfc). */
interface FlattenedTag extends Tag {
}

/** OmniFocus 'sidebar tree' class (sdef code: FCst). */
interface SidebarTree extends Tree {
  /** [read-only] The list of possible smart group identifiers that can be set as the selected smart group identifier. */
  availableSmartGroupIdentifiers(): unknown;
  /** The currently selected smart group identifier. */
  selectedSmartGroupIdentifier(): string;
}

/** OmniFocus 'content tree' class (sdef code: FCCt). */
interface ContentTree extends Tree {
  /** [read-only] The list of possible identifiers that can be set as the selected grouping identifier. */
  availableGroupingIdentifiers(): unknown;
  /** The currently selected grouping identifier, controlling how the results shown in the content area are grouped. */
  selectedGroupingIdentifier(): string;
  /** [read-only] The list of possible identifiers that can be set as the selected sorting identifier. */
  availableSortingIdentifiers(): unknown;
  /** The currently selected sorting identifier, controlling how the results shown in the content area are ordered. */
  selectedSortingIdentifier(): string;
  /** [read-only] The list of possible identifiers that can be set as the selected task state filter identifier. */
  availableTaskStateFilterIdentifiers(): unknown;
  /** The currently selected task state filter identifier. */
  selectedTaskStateFilterIdentifier(): string;
  /** [read-only] The list of possible identifiers that can be set as the selected task duration filter identifier. */
  availableTaskDurationFilterIdentifiers(): unknown;
  /** The currently selected task duration filter identifier. */
  selectedTaskDurationFilterIdentifier(): string;
  /** [read-only] The list of possible identifiers that can be set as the selected task flagged filter identifier. */
  availableTaskFlaggedFilterIdentifiers(): unknown;
  /** The currently selected task flagged filter identifier. */
  selectedTaskFlaggedFilterIdentifier(): string;
}

/** OmniFocus 'inbox tree' class (sdef code: FCIs). */
interface InboxTree extends Tree {
}

/** OmniFocus 'library tree' class (sdef code: FCLt). */
interface LibraryTree extends Tree {
}

/** OmniFocus 'perspective' class (sdef code: FCoo). */
interface Perspective {
  /** The identifier of the perspective. */
  id(): string;
  /** The name of the perspective. */
  name(): string;
}

/** OmniFocus 'builtin perspective' class (sdef code: FCbp). */
interface BuiltinPerspective extends Perspective {
}

/** OmniFocus 'custom perspective' class (sdef code: FCcp). */
interface CustomPerspective extends Perspective {
}

/** OmniFocus 'tree' class (sdef code: OTtr). */
interface Tree {
  /** [read-only] The name of the object being represented by this tree. */
  name(): string;
  /** [read-only] The identifier of object being represented by this tree. */
  id(): string;
  /** [read-only] The object being represented by this tree. */
  value(): unknown;
  /** This is true if the node is selected. Note that attempts to set this while the node is not visible (collapsed parent, etc.) will silently do nothing. */
  selected(): boolean;
  /** This is true if the node is expanded. */
  expanded(): boolean;
  /** This is true if the node note is expanded. */
  noteExpanded(): boolean;
  /** A list of the types that can be used when writing nodes to the pasteboard (i.e., copying). */
  writablePasteboardTypes(): unknown;
  /** A list of the types that can be used when reading nodes from the pasteboard (i.e., pasteing). */
  readablePasteboardTypes(): unknown;
  /** child collection of 'tree' */
  trees: JxaCollection<Tree> & (() => JxaCollection<Tree>);
  /** child collection of 'descendant tree' */
  descendantTrees: JxaCollection<DescendantTree> & (() => JxaCollection<DescendantTree>);
  /** child collection of 'ancestor tree' */
  ancestorTrees: JxaCollection<AncestorTree> & (() => JxaCollection<AncestorTree>);
  /** child collection of 'leaf' */
  leafs: JxaCollection<Leaf> & (() => JxaCollection<Leaf>);
  /** child collection of 'preceding sibling' */
  precedingSiblings: JxaCollection<PrecedingSibling> & (() => JxaCollection<PrecedingSibling>);
  /** child collection of 'following sibling' */
  followingSiblings: JxaCollection<FollowingSibling> & (() => JxaCollection<FollowingSibling>);
  /** child collection of 'selected tree' */
  selectedTrees: JxaCollection<SelectedTree> & (() => JxaCollection<SelectedTree>);
}

/** OmniFocus 'descendant tree' class (sdef code: OTds). */
interface DescendantTree extends Tree {
}

/** OmniFocus 'ancestor tree' class (sdef code: OTan). */
interface AncestorTree extends Tree {
}

/** OmniFocus 'leaf' class (sdef code: OTlf). */
interface Leaf extends Tree {
}

/** OmniFocus 'following sibling' class (sdef code: OTfs). */
interface FollowingSibling extends Tree {
}

/** OmniFocus 'preceding sibling' class (sdef code: OTps). */
interface PrecedingSibling extends Tree {
}

/** OmniFocus 'selected tree' class (sdef code: OTst). */
interface SelectedTree extends Tree {
}

/** OmniFocus 'style' class (sdef code: OSst). */
interface Style {
  /** [read-only] The object owning the style. */
  container(): unknown;
  /** The name of the font of the style. */
  font(): string;
  /** child collection of 'named style' */
  namedStyles: JxaCollection<NamedStyle> & (() => JxaCollection<NamedStyle>);
  /** child collection of 'attribute' */
  attributes: JxaCollection<Attribute> & (() => JxaCollection<Attribute>);
}

/** OmniFocus 'attribute' class (sdef code: OSsa). */
interface Attribute {
  /** [read-only] The name of the attribute. */
  name(): string;
  /** The style to which the attribute refers. */
  style(): Style;
  /** [read-only] If true, the containing style defines a local value for this attribute. */
  hasLocalValue(): boolean;
  /** [read-only] The style responsible for the effective value in this attributes's style. This processes the local values, inherited styles and cascade chain. */
  definingStyle(): Style;
  /** The value of the attribute in its style. */
  value(): unknown;
  /** The default value of the attribute in its style. */
  defaultValue(): unknown;
}

/** OmniFocus 'named style' class (sdef code: OSns). */
interface NamedStyle extends Style {
  /** [read-only] An identifier for the named style that is unique within its document. Currently this identifier is not persistent between two different sessions of editing the document. */
  id(): string;
  /** The name of the style. Must be unique within the containing document. */
  name(): string;
}

/** OmniFocus 'rich text' class (sdef code: OSrt). */
interface RichText {
  /** The plain text contents of the rich text. */
  text(): string;
  /** The color of the first character. */
  color(): unknown;
  /** The name of the font of the first character. */
  font(): string;
  /** The size in points of the first character. */
  size(): number;
  /** The style of the text. */
  style(): Style;
  /** Number of pixels shifted above or below the normal baseline. */
  baselineOffset(): number;
  /** The superscript level of the text. */
  superscript(): number;
  /** Alignment of the text. */
  alignment(): unknown;
  /** child collection of 'character' */
  characters: JxaCollection<Character> & (() => JxaCollection<Character>);
  /** child collection of 'paragraph' */
  paragraphs: JxaCollection<Paragraph> & (() => JxaCollection<Paragraph>);
  /** child collection of 'word' */
  words: JxaCollection<Word> & (() => JxaCollection<Word>);
  /** child collection of 'attribute run' */
  attributeRuns: JxaCollection<AttributeRun> & (() => JxaCollection<AttributeRun>);
  /** child collection of 'attachment' */
  attachments: JxaCollection<Attachment> & (() => JxaCollection<Attachment>);
  /** child collection of 'file attachment' */
  fileAttachments: JxaCollection<FileAttachment> & (() => JxaCollection<FileAttachment>);
}

/** OmniFocus 'character' class (sdef code: cha ). */
interface Character extends RichText {
}

/** OmniFocus 'paragraph' class (sdef code: cpar). */
interface Paragraph extends RichText {
}

/** OmniFocus 'word' class (sdef code: cwor). */
interface Word extends RichText {
}

/** OmniFocus 'attribute run' class (sdef code: catr). */
interface AttributeRun extends RichText {
}

/** OmniFocus 'attachment' class (sdef code: atts). */
interface Attachment extends RichText {
}

/** OmniFocus 'file attachment' class (sdef code: OSfA). */
interface FileAttachment extends Attachment {
  /** [read-only] The path to the file for the attachment, if the attachment resides outside the document. */
  fileName(): unknown;
  /** [read-only] If true, the attached file will reside inside the document on the next save. */
  embedded(): boolean;
}

/** OmniFocus 'preference' class (sdef code: OFpf). */
interface Preference {
  /** [read-only] The identifier of the preference. */
  id(): string;
  /** The current value of the preference. */
  value(): string;
  /** The default value of the preference. */
  defaultValue(): string;
}
