#!/usr/bin/env tsx
/**
 * Generates src/tools/INDEX.md — one line per tool, grouped by domain.
 *
 * Usage:
 *   pnpm run docs:generate-index          # write the file
 *   pnpm run docs:check-index             # exit non-zero if file is stale
 *
 * The "1-line summary" is the first sentence of the tool description
 * (up to the first ". " or end of first line), which descriptionShape.ts
 * already validates as required content.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_TOOL_DESCRIPTIONS } from "../src/tools/allDescriptions.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "..", "src", "tools", "INDEX.md");

const CHECK_MODE = process.argv.includes("--check");

// ---------------------------------------------------------------------------
// Extract 1-line summary from a tool description
// ---------------------------------------------------------------------------

const MAX_SUMMARY_LEN = 60;

function extractSummary(description: string): string {
  // Take everything up to the first ". " or "\n", trimmed.
  const firstPeriod = description.indexOf(". ");
  const firstNewline = description.indexOf("\n");

  let end = description.length;
  if (firstPeriod !== -1) end = Math.min(end, firstPeriod + 1);
  if (firstNewline !== -1) end = Math.min(end, firstNewline);

  let summary = description.slice(0, end).trim().replace(/\.$/, "");

  // Trim to MAX_SUMMARY_LEN, breaking at the last word boundary.
  if (summary.length > MAX_SUMMARY_LEN) {
    const truncated = summary.slice(0, MAX_SUMMARY_LEN);
    const lastSpace = truncated.lastIndexOf(" ");
    summary = `${lastSpace > 0 ? truncated.slice(0, lastSpace) : truncated}…`;
  }

  return summary;
}

// ---------------------------------------------------------------------------
// Group tools by domain (first underscore-delimited segment)
// ---------------------------------------------------------------------------

function domainOf(toolName: string): string {
  const idx = toolName.indexOf("_");
  return idx === -1 ? toolName : toolName.slice(0, idx);
}

// Preferred domain ordering (mirrors directory listing)
const DOMAIN_ORDER = [
  "task",
  "project",
  "tag",
  "folder",
  "forecast",
  "perspective",
  "note",
  "search",
  "attachment",
  "sync",
  "review",
  "database",
  "webhook",
  "window",
  "app",
  "plugin",
  "export",
  "import",
  "repetition",
  "decision",
  "rawScript",
  "clarify",
  "internal",
];

// ---------------------------------------------------------------------------
// Build index
// ---------------------------------------------------------------------------

interface ToolEntry {
  name: string;
  summary: string;
}

const byDomain = new Map<string, ToolEntry[]>();

for (const [name, description] of Object.entries(ALL_TOOL_DESCRIPTIONS)) {
  const domain = domainOf(name);
  if (!byDomain.has(domain)) byDomain.set(domain, []);
  byDomain.get(domain)!.push({ name, summary: extractSummary(description) });
}

// Sort tools within each domain alphabetically
for (const entries of byDomain.values()) {
  entries.sort((a, b) => a.name.localeCompare(b.name));
}

// Order domains: known order first, then any unknown ones alphabetically
const orderedDomains = [
  ...DOMAIN_ORDER.filter((d) => byDomain.has(d)),
  ...[...byDomain.keys()].filter((d) => !DOMAIN_ORDER.includes(d)).sort(),
];

// ---------------------------------------------------------------------------
// Render markdown
// ---------------------------------------------------------------------------

const totalTools = [...byDomain.values()].reduce((n, v) => n + v.length, 0);

const lines: string[] = [
  "<!-- generated by scripts/generate-tool-index.ts — do not edit manually -->",
  "# src/tools/INDEX.md",
  "",
  `${totalTools} tools grouped by domain. Use this file to find a tool without grepping.`,
  "Each line: **tool\\_name** — 1-line summary. Source path: `src/tools/<domain>/<verb>.ts`.",
  "",
];

for (const domain of orderedDomains) {
  const entries = byDomain.get(domain)!;
  lines.push(`## ${domain}`);
  lines.push("");
  for (const { name, summary } of entries) {
    lines.push(`- **${name}** — ${summary}`);
  }
  lines.push("");
}

const content = lines.join("\n");

// ---------------------------------------------------------------------------
// Write or check
// ---------------------------------------------------------------------------

if (CHECK_MODE) {
  const existing = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, "utf8") : "";
  if (existing !== content) {
    console.error("src/tools/INDEX.md is out of date. Run: pnpm run docs:generate-index");
    process.exit(1);
  }
  console.log("src/tools/INDEX.md is up to date.");
} else {
  fs.writeFileSync(OUT_PATH, content, "utf8");
  console.log(`Generated ${OUT_PATH} (${totalTools} tools, ${content.length} bytes)`);
}
