/**
 * Sanity tests for the JXA-types generator (#854).
 *
 * These don't re-run the generator — they verify the committed output at
 * `src/scripts/jxa/_types/omnifocus.d.ts` matches the contract documented
 * in `docs/spikes/2026-05-jxa-static-typing.md`. If the file drifts from
 * the snapshot, `pnpm generate:jxa-types` reproduces it.
 *
 * The committed `.d.ts` IS the gate: this test catches the case where
 * someone hand-edits the file (which would be silently re-overwritten on
 * the next regenerate), or where a bad snapshot loses critical signal
 * (the OF 4.x quirks documented in `src/scripts/jxa/CLAUDE.md`).
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const DTS = readFileSync("src/scripts/jxa/_types/omnifocus.d.ts", "utf8");

function interfaceBody(name: string): string {
  const re = new RegExp(`^interface ${name}[^\\n]*\\{([\\s\\S]*?)^\\}`, "m");
  const m = DTS.match(re);
  if (!m || m[1] === undefined) {
    throw new Error(`interface ${name} not found in generated .d.ts`);
  }
  return m[1];
}

describe("omnifocus.d.ts — header invariants", () => {
  it("declares it was auto-generated", () => {
    expect(DTS).toMatch(/AUTO-GENERATED by scripts\/generate-jxa-types\.ts/);
  });

  it("points at the pinned sdef snapshot", () => {
    expect(DTS).toMatch(/Source: vendor\/OmniFocus\.sdef/);
  });

  it("covers the full sdef (47 classes per OF 4.x)", () => {
    expect(DTS).toMatch(/Coverage: 47 classes/);
  });
});

describe("omnifocus.d.ts — OF 4.x quirk invariants", () => {
  // These are the exact bug-detections that motivated the generator.
  // See src/scripts/jxa/CLAUDE.md and docs/spikes/2026-05-jxa-static-typing.md.

  it("Folder has NO `parent()` (use container() instead — #515)", () => {
    expect(interfaceBody("Folder")).not.toMatch(/^\s*parent\(\):/m);
  });

  it("Folder DOES have `container()`", () => {
    expect(interfaceBody("Folder")).toMatch(/^\s*container\(\):/m);
  });

  it("Tag has NO `parent()` (use container() instead)", () => {
    expect(interfaceBody("Tag")).not.toMatch(/^\s*parent\(\):/m);
  });

  it("Tag has NO `containingTag()` (use container() instead)", () => {
    expect(interfaceBody("Tag")).not.toMatch(/^\s*containingTag\(\):/m);
  });

  it("Tag DOES have `container()`", () => {
    expect(interfaceBody("Tag")).toMatch(/^\s*container\(\):/m);
  });
});

describe("omnifocus.d.ts — shape", () => {
  it("Task interface emits at least 20 properties (sanity-check coverage)", () => {
    const body = interfaceBody("Task");
    const propLines = body.split("\n").filter((l) => /^\s*\w+\(\):/.test(l));
    expect(propLines.length).toBeGreaterThanOrEqual(20);
  });

  it("entity references resolve to interface names (not `unknown`)", () => {
    // Folder.container() should return Document (the first union member).
    // If the parser regressed and stopped reading nested <type> children,
    // this would be `unknown` and the test fails loudly.
    expect(interfaceBody("Folder")).toMatch(/container\(\): Document/);
  });

  it("includes the Application interface at the top of the hierarchy", () => {
    expect(DTS).toMatch(/^interface Application/m);
  });
});
